defaults:
  - sim_config: base_sim_config
  - mpc_config: base_mpc_config
  - optitrack_config: tee_optitrack_config
  - realsense_config: top_front_realsense
  - hydra: base_hydra

sim_config:
  use_hardware: False
  closed_loop: False

trajectory_set_name: "hw_demos_20240129115732_tee"
trajectory_index: 1
use_rounded: True
# override_duration: 5

save_experiment_data: True

hydra:
  mode: MULTIRUN
  sweeper:
    params:
      trajectory_index: 0, 1, 2, 3, 9
      sim_config.closed_loop: False, True
# 1, 2, 3, 5, 6, 7, 8
# 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13