defaults:
  - sim_config: base_sim_config
  - mpc_config: base_mpc_config
  - optitrack_config: tee_optitrack_config
  - realsense_config: top_front_realsense
  - hydra: base_hydra

sim_config:
  use_hardware: False
  closed_loop: True

trajectory_set_name: "hw_demos_20240125152221_tee_socp"
use_rounded: True
override_duration: 5

save_experiment_data: True

hydra:
  mode: MULTIRUN
  sweeper:
    params:
      trajectory_index: 9, 10