defaults:
  - sim_config: base_sim_config
  - mpc_config: base_mpc_config
  - optitrack_config: tee_optitrack_config
  - realsense_config: top_front_side_realsense
  - hydra: base_hydra

sim_config:
  time_step: 5e-3
  use_hardware: True
  closed_loop: True
  save_plots: True
  use_realtime: True
  visualize_desired: True

mpc_config:
  rate_Hz: 200

trajectory_set_name: "hw_demos_20240129170214_tee" # "hw_demos_20240129170214_tee"
trajectory_index: 1
use_rounded: True
# override_duration: 5

save_experiment_data: True

hydra:
  mode: MULTIRUN
  sweeper:
    params:
      trajectory_index: 0, 1, 2, 9, 14, 15, 17, 24, 25
      # sim_config.closed_loop: False, True
# 0, 1, 2, 9, 14, 15, 17, 24, 25