defaults:
  - sim_config: base_sim_config
  - mpc_config: base_mpc_config
  - optitrack_config: tee_optitrack_config
  - realsense_config: top_front_side_realsense
  - hydra: base_hydra

sim_config:
  time_step: 2e-2
  use_hardware: False
  closed_loop: False
  save_plots: False
  visualize_desired: False

trajectory_set_name: "hw_demos_20240129115732_tee"
trajectory_index: 2
use_rounded: True
# override_duration: 17

save_experiment_data: True