defaults:
  - sim_config: base_sim_config
  - mpc_config: base_mpc_config
  - optitrack_config: tee_optitrack_config
  - realsense_config: top_front_side_realsense
  - hydra: base_hydra

sim_config:
  time_step: 5e-3
  use_hardware: True
  closed_loop: True
  save_plots: False
  use_realtime: True
  visualize_desired: True

mpc_config:
  rate_Hz: 50
  step_size: 0.06
  horizon: 20
  Q: [3, 3, 0.01, 0]
  Q_scaling: 100
  Q_N: [3, 3, 0.01, 0]
  Q_N_scaling: 2000
  R: [1, 1, 0.01]
  R_scaling: 0.5
  u_max_magnitude: [4, 4, 2]

trajectory_set_name: "hw_demos_20240207195018_tee_seed_0"
trajectory_index: 7 # 1,3,5,8,9,10,11,15,16
use_rounded: True
# override_duration: 5

save_experiment_data: True

# "hw_demos_20240207195018_tee_seed_0"
# 0,1,2,5,7

# "hw_demos_20240129170214_tee"
# 0, 1, 2, 9, 14, 15, 17, 22, 24, 25

# "hw_demos_20240207141104_tee_fixed_bugs"
# 0,1,5,8,11,13,16,17,20,21
# poor performance: 5, 13

# "hw_demos_20240207160247_tee_more_hardware"
# 0,1,3,4,5,6,8,9,10